export const FETCH_JOBS = 'FETCH_JOBS';
export const FETCH_JOBS_SUCCESSFULLY = 'FETCH_JOBS_SUCCESSFULLY';

export const SAVE_JOB = 'SAVE_JOB';
export const SAVE_JOB_SUCCESSFULLY = 'SAVE_JOB_SUCCESSFULLY';

export const REMOVE_JOB = 'REMOVE_JOB';
export const REMOVE_JOB_SUCCESSFULLY = 'REMOVE_JOB_SUCCESSFULLY';

export const UPDATE_JOB = 'UPDATE_JOB';
export const UPDATE_JOB_SUCCESSFULLY = 'UPDATE_JOB_SUCCESSFULLY';

export const SEARCH_JOB = 'SEARCH_JOB';
export const SEARCH_JOB_SUCCESSFULLY = 'SEARCH_JOB_SUCCESSFULLY';
