export const FETCH_JOBS = 'FETCH_JOBS';
export const FETCH_JOBS_SUCCESSFULLY = 'FETCH_JOBS_SUCCESSFULLY';
export const FETCH_JOBS_ERROR = 'FETCH_JOBS_ERROR';

export const SAVE_JOB = 'SAVE_JOB';
export const SAVE_JOB_SUCCESSFULLY = 'SAVE_JOB_SUCCESSFULLY';
export const SAVE_JOB_ERROR = 'SAVE_JOB_ERROR';

export const REMOVE_JOB = 'REMOVE_JOB';
export const REMOVE_JOB_SUCCESSFULLY = 'REMOVE_JOB_SUCCESSFULLY';
export const REMOVE_JOB_ERROR = 'REMOVE_JOB_ERROR';
