export const context = 'jobs';

export const CREATE_JOB_AUTOMATICALLY = 'CREATE_JOB_AUTOMATICALLY';
export const SAVE_JOB = 'SAVE_JOB';
export const REMOVE_JOB = 'REMOVE_JOB';
export const UPDATE_JOB = 'UPDATE_JOB';
export const SEARCH_JOB = 'SEARCH_JOB';
export const SEARCH_JOB_SUCCESSFULLY = 'SEARCH_JOB_SUCCESSFULLY';
export const FETCH_JOBS_SUCCESSFULLY = 'FETCH_JOBS_SUCCESSFULLY';
